--1) addres tablosunun kontrol etmek için top 100 ünü çekiniz.
SELECT top 100 * FROM [dbo].[adres]
--2)CITIES tablosuna yeni bir kayýt olarak ID,COUNTRYID VE memlektenizi ekleyin.
INSERT INTO
CITIES
( ID, COUNTRYID, COUNTRY)
VALUES
(1010,10,'BALIKESIR')
--3)[dbo].[USERS] tablosundaki 10 numaralý id yi kendi bilgileriniz ile update edin.
SELECT * FROM USERS 
UPDATE USERS
SET  USERNAME_='ERDOGAN', PASSWORD_='PASSWORD123', NAMESURNAME='FATMA ERDOGAN', EMAIL='F_ERDOGAN@sqlegitimbtk.com', GENDER='K', BIRTHDATE='31.08.1998', CREATEDDATE='25.07.2018 01:35', TELNR2='5500000000', AGE=26 WHERE ID=10

SELECT top 100 * FROM [dbo].[users]

--4)[dbo].[SALEORDERS] tablosunda category1 i SEKERLEME OLAN KAYITLARI GETÝRÝN.

SELECT * FROM [dbo].[SALEORDERS] WHERE CATEGORY1='SEKERLEME'

--5)[dbo].[SALEORDERS] tablosunda LINETOTALI 20.000 DEN BUYUK KAYITLARI GETIRIN.

SELECT * FROM [dbo].[SALEORDERS] WHERE LINETOTAL>20.000

--6)[dbo].[SALEORDERS] tablosunda haftaiçi olan kayýtlarý getirin.

SELECT * FROM [dbo].[SALEORDERS] 
WHERE DATENAME(WEEKDAY, DATE_) NOT IN ('Saturday', 'Sunday');

SELECT * FROM [dbo].[SALEORDERS] 
WHERE DATEPART(WEEKDAY, DATE_) BETWEEN 2 AND 6;

SELECT DISTINCT DAYOFWEEK_ FROM SALEORDERS
SELECT * FROM SALEORDERS WHERE DAYOFWEEK_ NOT IN ('Pazar', 'Cumartesi')
	
--7)[dbo].[SALEORDERS] tablosunda pazar günü ve Tablet satýþlarýný getirin.
SELECT * FROM [dbo].[SALEORDERS] 
WHERE DATENAME(WEEKDAY, DATE_) = 'Sunday'
AND CATEGORY4 = 'Tablet';

--8)[dbo].[ITEMS]tablosunda kaç tane tekin category1 vardýr.

SELECT COUNT(DISTINCT CATEGORY1) AS TekilCategory1Sayisi
FROM [dbo].[items]

--9)[dbo].[ITEMS]tablosundaki ürünleri unitprice a göre büyükten küçüðe sýralayýnýz.

SELECT * FROM [dbo].[items]ORDER BY unitprice DESC 

--10)[dbo].[SALEORDERS] tablosunda þehirlere göre (SUM,COUNT,MIN,MAX,AVG) adeti getirin.

SELECT 
    CITY,
    SUM(AMOUNT) AS ToplamAdet,
    COUNT(*) AS SiparisSayisi,
    MIN(AMOUNT) AS MinimumAdet,
    MAX(AMOUNT) AS MaksimumAdet,
    AVG(AMOUNT) AS OrtalamaAdet
FROM [dbo].[SALEORDERS]
GROUP BY CITY;

--11) ÜRÜN KATEGORÝLERÝNE GÖRE TOPLAM SATIÞLARý getirin.
SELECT CATEGORY1,CATEGORY2,CATEGORY3,SUM(AMOUNT)AS ADET FROM [dbo].[SALEORDERS]
GROUP BY CATEGORY1,CATEGORY2,CATEGORY3

SELECT CATEGORY1, CATEGORY2, SUM(AMOUNT), SUM(LINETOTAL)
FROM [dbo].[ORDERS] o
INNER JOIN [dbo].[ORDERDETAILS] od ON o.ID = od.ORDERID
INNER JOIN ITEMS ITM ON ITM.ID = od.ITEMID
GROUP BY CATEGORY1, CATEGORY2

--12)order ve user tablolarýný left,right ve inner olarak þekilde birleþtiriniz.

-- LEFT INCLUSIVE
SELECT *
FROM [dbo].[orders]
LEFT OUTER JOIN [dbo].[users]
  ON [dbo].[orders].USERID = [dbo].[users].ID;

-- RIGHT INCLUSIVE
SELECT *
FROM [dbo].[orders]
RIGHT OUTER JOIN [dbo].[users]
  ON [dbo].[orders].USERID = [dbo].[users].ID;

-- INNER JOIN
SELECT *
FROM [dbo].[orders]
INNER JOIN [dbo].[users]
  ON [dbo].[orders].USERID = [dbo].[users].ID;

--13)adress ve user tablolarýný left,right ve inner olarak þekilde birleþtiriniz.

-- LEFT INCLUSIVE
SELECT *
FROM [dbo].[adres]
LEFT OUTER JOIN [dbo].[users]
  ON [dbo].[adres].USERID = [dbo].[users].ID;

-- RIGHT INCLUSIVE
SELECT *
FROM [dbo].[adres]
RIGHT OUTER JOIN [dbo].[users]
  ON [dbo].[adres].USERID = [dbo].[users].ID;

-- INNER JOIN
SELECT *
FROM [dbo].[adres]
INNER JOIN [dbo].[users]
  ON [dbo].[adres].USERID = [dbo].[users].ID;

--14)En fazla alýþveriþ hangi markada yapýlmýþtýr.

SELECT BRAND,SUM(LINETOTAL)MARKATOPLAMCIRO FROM ORDERS O
INNER JOIN ORDERDETAILS OD ON O.ID=OD.ORDERID
INNER JOIN ITEMS IT ON IT.ID=OD.ITEMID
GROUP BY BRAND ORDER BY 2 DESC

--15)oyuncak ANA KATEGORÝSÝNDE KATEGORÝSÝNDE, ZEKA GELISTIRICI UST KATEGORISINDE,OYUNCAKLAR ALT KATEGORISINDE EN FAZLA SATIÞ YAPAN, bebe oyuncaklarý nelerdir?

SELECT ITEMNAME,SUM(AMOUNT)BEBEKOYUNCAKLARISATIS FROM ORDERS O
INNER JOIN ORDERDETAILS OD ON O.ID=OD.ORDERID
INNER JOIN ITEMS IT ON IT.ID=OD.ITEMID
WHERE CATEGORY1='OYUNCAK' AND CATEGORY2='ZEKA GELISTIRICI' AND CATEGORY3='OYUNCAKLAR' AND CATEGORY4='BEBE OYUNCAK'
GROUP BY ITEMNAME ORDER BY 2 DESC

--16) TEMIZLIK KATEGORÝSÝNDEKI URUNLERIN ORTALAMA FÝYAT NEDÝR

SELECT 
CATEGORY1,
SUM(LINETOTAL) AS CIRO,
SUM(AMOUNT) AS ADET, 
SUM(LINETOTAL)/SUM(AMOUNT) AS ORTFIYAT
FROM ORDERS O
INNER JOIN ORDERDETAILS OD ON O.ID=OD.ORDERID
INNER JOIN ITEMS IT ON IT.ID=OD.ITEMID
WHERE CATEGORY1='TEMIZLIK'
GROUP BY CATEGORY1


SELECT ITEMNAME, AVG(TOTALPRICE) 
FROM [dbo].[ORDERS] o
INNER JOIN [dbo].[ORDERDETAILS] od ON o.ID = od.ORDERID
INNER JOIN ITEMS ITM ON ITM.ID = od.ITEMID
WHERE CATEGORY1 = 'TEMİZLİK'
GROUP BY ITEMNAME

--17) HANGÝ YAÞ GRUPLARI DAHA FAZLA ALIÞVERÝÞ YAPMIÞtýr

SELECT AGE, SUM(AMOUNT) AS TOPLAMADET
FROM ORDERS O
INNER JOIN ORDERDETAILS OD ON O.ID = OD.ORDERID
INNER JOIN USERS U ON U.ID = O.USERID
INNER JOIN ITEMS IT ON IT.ID = OD.ITEMID
GROUP BY AGE
ORDER BY TOPLAMADET DESC;


SELECT AGE, SUM(TOTALPRICE) 
FROM [dbo].[ORDERS] o
INNER JOIN USERS U ON o.USERID = U.ID
GROUP BY AGE 
ORDER BY 2 DESC

--18)[dbo].[ITEMS] TABLOSUNDAKÝ TÜM CATERGORYLERÝ BÝRLEÞTÝRÝN.

SELECT CATEGORY1 AS CATEGORY FROM [dbo].[items]
UNION ALL
SELECT CATEGORY2 FROM [dbo].[items]
UNION ALL
SELECT CATEGORY3 FROM [dbo].[items]
UNION ALL
SELECT CATEGORY4 FROM [dbo].[items]


SELECT CONCAT(CATEGORY1, '-', CATEGORY2, '-', CATEGORY3, '-', CATEGORY4) AS FULL_CATEGORY 
FROM ITEMS
	
--19)[dbo].[PAYMENTS] TABLOSUNDAKÝ APPROVECODE KOLONUNUN ILK 5 DEÐERÝNÝ AYRI BÝR KOLON OLARAK YAZIN.

SELECT 
    MAX(CASE WHEN ROW_NUMBER = 1 THEN APPROVECODE END) AS ApproveCode1,
    MAX(CASE WHEN ROW_NUMBER = 2 THEN APPROVECODE END) AS ApproveCode2,
    MAX(CASE WHEN ROW_NUMBER = 3 THEN APPROVECODE END) AS ApproveCode3,
    MAX(CASE WHEN ROW_NUMBER = 4 THEN APPROVECODE END) AS ApproveCode4,
    MAX(CASE WHEN ROW_NUMBER = 5 THEN APPROVECODE END) AS ApproveCode5
FROM (
    SELECT APPROVECODE, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS ROW_NUMBER
    FROM [dbo].[PAYMENTS]
) AS temp;


SELECT LEFT(APPROVECODE, 5) 
FROM PAYMENTS

--20)[dbo].[PAYMENTS] TABLOSUNDAKÝ SAYISAL DEÐERLERÝ AYRI BÝR KOLON OLARAK YAZIN.

SELECT 
    APPROVECODE,
    CASE 
        WHEN ISNUMERIC(APPROVECODE) = 1 THEN APPROVECODE
        ELSE NULL
    END AS SAYISAL_DEGER
FROM PAYMENTS;


SELECT SUBSTRING(APPROVECODE, 6, LEN(APPROVECODE) - 5) 
FROM PAYMENTS

SELECT RIGHT(APPROVECODE, 9) 
FROM PAYMENTS

--21)[dbo].[USERS] TABLOSUNDAKÝ PASSWORD KOLONUNU TÜM DEÐERLERÝ BÜYÜK YAZIN.

SELECT UPPER(PASSWORD_)BUYUKISIM,* FROM USERS

--22)[dbo].[USERS] TABLOSUNDAKÝ NAMESURNAME  KOLONUNUNDAKÝ SOYÝSÝMLERÝ TÜM DEÐERLERÝ KÜÇÜK YAZIN.

SELECT CONCAT(
    LEFT(NAMESURNAME, CHARINDEX(' ', NAMESURNAME)), -- Ad kısmı (boşluk dahil)
    LOWER(SUBSTRING(NAMESURNAME, CHARINDEX(' ', NAMESURNAME) + 1, LEN(NAMESURNAME))) -- Soyad kısmı (küçük harf)
) 
FROM USERS

--23)[dbo].[INVOICES] TABLOSUNDAKÝ DATE KOLONUNU AÞAÐIDAKÝ FORMATLARA ÇEVÝRÝN.

--mm/dd/yyyy
SELECT CONVERT(varchar,DATE_,101)TARIH,DATE_ FROM [dbo].[INVOICES]

--yyyy.mm.dd
select CONVERT(varchar,DATE_,102),DATE_ from [dbo].[INVOICES]

---dd.mm.yyyy
select CONVERT(varchar,DATE_,104),DATE_ from [dbo].[INVOICES]

---dd mon yyyy
select CONVERT(varchar,DATE_,106),DATE_ from [dbo].[INVOICES]

--hh:mm:ss
select CONVERT(varchar,DATE_,112),DATE_ from [dbo].[INVOICES]

--yyyymmdd
select CONVERT(varchar,DATE_,10),DATE_ from [dbo].[INVOICES]

--24)[dbo].[INVOICES] TABLOSUNDAKÝ DATE KOLONUNU YIL,AY,GUN,HAFTA OLARAK AYRI AYIR KOLONLARDA GÖSTERÝN.

SELECT DATEPART(YEAR,DATE_)YIL, DATEPART(MONTH,DATE_)AY,DATEPART(DAY,DATE_)GUN DATE_ FROM [dbo].[INVOICES] 

--25)[dbo].[SALEORDERS] TABLOSUNDAKÝ MONTH KOLONUNA GÖRE HANGÝ AYIN HANGÝ MEVSÝME GELDÝÐÝNÝ YAZIN.

SELECT DATEPART(MONTH,CONVERT(DATE, DATE_))AY FROM [dbo].[SALEORDERS]

SELECT 
CASE 
    WHEN DATEPART(MONTH, CONVERT(DATE, DATE_)) BETWEEN 1 AND 2 OR DATEPART(MONTH, CONVERT(DATE, DATE_)) = 12 THEN 'KIS'
    WHEN DATEPART(MONTH, CONVERT(DATE, DATE_)) BETWEEN 3 AND 5 THEN 'ILKBAHAR'
    WHEN DATEPART(MONTH, CONVERT(DATE, DATE_)) BETWEEN 6 AND 8 THEN 'YAZ'
    WHEN DATEPART(MONTH, CONVERT(DATE, DATE_)) BETWEEN 9 AND 11 THEN 'SONBAHAR'
    ELSE 'BOS'
END AS MEVSIM,
DATEPART(MONTH, CONVERT(DATE, DATE_)) AS AY
FROM [dbo].[SALEORDERS];

SELECT 
    CASE 
        WHEN MONTH_ IN ('Aralık', 'Ocak', 'Şubat') THEN 'Kış'
        WHEN MONTH_ IN ('Mart', 'Nisan', 'Mayıs') THEN 'İlkbahar'
        WHEN MONTH_ IN ('Haziran', 'Temmuz', 'Ağustos') THEN 'Yaz'
        WHEN MONTH_ IN ('Eylül', 'Ekim', 'Kasım') THEN 'Sonbahar'
        ELSE 'Bilinmiyor'
    END AS MEVSIM
FROM dbo.SALEORDERS


--26)[dbo].[ITEMS] TABLOSUDNAKÝ BRANLERÝ AÞAÐIDAKÝ KURALA GÖRE YENÝ BÝR KOLON OLUÞTURUNUZ.
		--ULKER ISE YEME ICME
		--REXONA ISE KOZMATIK
		--ALGIDA ISE DONDURMA
		--NESCAFE ISE SICAKICECEK
		--BUNLARIN DIÞINDAKILER DIGER 

SELECT *,
CASE 
    WHEN BRAND = 'ULKER' THEN 'YEME ICME'
    WHEN BRAND = 'REXONA' THEN 'KOZMATIK'
    WHEN BRAND = 'ALGIDA' THEN 'DONDURMA'
    WHEN BRAND = 'NESCAFE' THEN 'SICAKICECEK'
    ELSE 'DIGER'
END AS YENIKATEGORI
FROM [dbo].[items]
